### ISSUE TITLE
what is the initial setting of m,n in FFMwithAdag.train()?

### ISSUE THREAD

**Issue by neal668** [Intel-bigdata/FFM-Spark#1]
Hi, Firstly thank you for the implementation and package.
I used this package and initial data for testing, their is an error shown below.

Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;
        at org.apache.spark.mllib.classification.FFMWithAdag.generateInitWeights(FFMWithAdag.scala:24)
        at org.apache.spark.mllib.classification.FFMWithAdag.run(FFMWithAdag.scala:55)
        at org.apache.spark.mllib.classification.FFMWithAdag$.train(FFMWithAdag.scala:77)
        at TestFFM$.main(TestFFM.scala:39)
        at TestFFM.main(TestFFM.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

I suppose this may caused by the below code 
`val ffm: FFMModel = FFMWithAdag.train(training, _m, n_, param, "adagrad")`
the m and n in this line seem have no pre-define and didn't require user input. 
Is this the reason led this error or are there any place I made wrong?
My compiler is IntelliJ IDEA and the test system is Centos 6.6
Thank you for your time.

**Comment by VinceShieh** [comment]
@neal668 Did u change the code? I can not locate the exact line of code with the log you attached.
this seems like not an issue related with m, n, it's  java.lang.NoSuchMethodError.
please also provide the test procedure so that we can reproduce on our end.

**Comment by VinceShieh** [comment]
@neal668 it seems the code is outdated. We move the repo to 
https://github.com/Intel-bigdata/imllib-spark
which will be keep updated.
Could you please try the FFM there?
sorry for all the trouble ;)

**Comment by neal668** [comment]
@VinceShieh  Thank you, I will try this FFM implementation. :+1:

**Comment by VinceShieh** [comment]
you are welcome. Feel free to let us know if any problem.
close this one for now.
